### PR TITLE
Gallery layout

### PR DESCRIPTION
**Pull request by yy4382**
- [x] click image to show dialog
- [x] better checkbox
- [x] Fix the issue that when element changes, layout is not automatically calculated.
- [x] Code standardization.

https://github.com/yy4382/s3-image-port/assets/55980292/4d365fcb-36ee-4c25-ab26-b5425511c96b

### CODE REVIEW

**Comment by yy4382** [comment]
Most of the planned features have been implemented. Borrowed (copied) many UI / UX designs from Google Photos.

@BlockLune What else buttons should we add to the toolbar in the photoCardModal?

**Comment by BlockLune** [comment]
image

**Comment by BlockLune** [comment]
Maybe a button to uncheck all selected should also be added?

**Comment by BlockLune** [comment]
Shouldn't it also show in photoCardModal whether the image is selected or not? Also, two arrow buttons should be added for switching images in photoCardModal.

**Comment by BlockLune** [comment]
The interface should add some loading animations. Right now the behavior is that first there will be a lot of fixed sized empty boxes, then the image loads (squeezed to show up as the size of the empty box), and finally the image transforms to the correct size.

**Comment by yy4382** [comment]
> image

background color is set to gray like Google Photos

the key text now has absolute position, so it's hard to tell the width

**Comment by yy4382** [comment]
> The interface should add some loading animations. Right now the behavior is that first there will be a lot of fixed sized empty boxes, then the image loads (squeezed to show up as the size of the empty box), and finally the image transforms to the correct size.

To get the natural size of image (which is used to calculate the layout), the image needs to be loaded in DOM first

**Comment by yy4382** [comment]
navigate between images in modal view requires a relative large refactor. It is of low priority.

New features won't be added in this PR.

If no bugs are found, I'll merge it.

**Pull request merged**
