### PR TITLE
Update Docs

### PR DESCRIPTION
**Pull request by BlockLune**
TODOs:

~~- [ ] Step-by-step guide for AWS S3~~ (Move to another PR)
- [x] Step-by-step guide for Cloudflare R2
- [x] New poster with better design

### CODE REVIEW

**Comment by yy4382** [comment]
Step-by-step guide can have a separate section in sidebar

**Comment by BlockLune** [comment]
> Step-by-step guide can have a separate section in sidebar

Yeah, but I don't know how to do that :sob:

**Comment by BlockLune** [comment]
I'd like to update the preview image in README, but it's best to do so after #61

**Comment by yy4382** [comment]
> > Step-by-step guide can have a separate section in sidebar
> 
> Yeah, but I don't know how to do that 😭

https://vitepress.dev/reference/default-theme-sidebar

**Comment by yy4382** [comment]
> I'd like to update the preview image in README, but it's best to do so after #61

That will need a while. Don't wait for that.

**Comment by BlockLune** [comment]
Is it a better practice to avoid the concept of "I" in a public document?

Refer to [用词恰当 — 中文技术文档写作风格指南](https://zh-style-guide.readthedocs.io/zh-cn/latest/%E8%AF%AD%E8%A8%80%E9%A3%8E%E6%A0%BC/%E7%94%A8%E8%AF%8D%E6%81%B0%E5%BD%93.html#id3)

image

**Comment by yy4382** [comment]
When will it be ready for review? Maybe "Step-by-step guide for AWS S3" should be in another PR.

**Comment by BlockLune** [comment]
> When will it be ready for review? Maybe "Step-by-step guide for AWS S3" should be in another PR.

Sorry Ive been very busy these days and have no time to deal with this pr

**Review by yy4382 — APPROVED** [review]

**Pull request merged**
